name: Esteira CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  analyse:
    name: An치lise com CodeQL
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ "java" ]

    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v4

      - name: Criar pasta para os relat칩rios
        run: mkdir -p reports/${{ github.ref_name }}

      - name: Cache Maven
        uses: ./.github/workflows/maven-cache.yml@main

      - name: Inicializar CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: ${{ matrix.language }}
          queries: security-extended,security-and-quality

      - name: Configurar JDK (Java 21) e compilar projeto com Maven
        uses: ./.github/workflows/maven-compile.yml@main

      - name: Executar an치lise de CodeQL
        uses: github/codeql-action/analyze@v4
        with:
          output: reports/${{ github.ref_name }}
          category: "/language:${{ matrix.language }}"

      - name: Renomear arquivo SARIF
        run: |
          ORIGINAL="reports/${{ github.ref_name }}/${{ matrix.language }}.sarif"
          NOVO="reports/${{ github.ref_name }}/codeql-results.sarif"
          mv "$ORIGINAL" "$NOVO"

      - name: Executar CLOC
        uses: djdefi/cloc-action@6
        with:
          options: --exclude-lang=YAML --md --report-file=cloc.md

      - name: Mover CLOC report
        run: mv cloc.md reports/${{ github.ref_name }}/cloc.md

      - name: Executar Checkstyle (Maven)
        run: mvn checkstyle:checkstyle

      - name: Preparar pasta para report do Checkstyle
        run: mkdir -p reports/${{ github.ref_name }}/checkstyle-result

      - name: Mover report Checkstyle
        run: |
          mv target/site/css reports/${{ github.ref_name }}/checkstyle-result/css
          mv target/site/images reports/${{ github.ref_name }}/checkstyle-result/images
          mv target/site/checkstyle.html reports/${{ github.ref_name }}/checkstyle-result

      - name: Executar SpotBugs
        run: mvn spotbugs:spotbugs

      - name: Mover report SpotBugs
        run: |
          mv target/spotbugsXml.xml reports/${{ github.ref_name }}/spotbugs.xml
          mv target/site/spotbugs.html reports/${{ github.ref_name }}/spotbugs.html

      - name: Executar testes
        run: |
          mvn test -Dgroups=!Selenium -B || {
            echo "::error::Alguns testes falharam. Revise os logs para detalhes.";
            exit 1;
          }

      - name: Mover report JaCoCo
        run: mv target/site/jacoco/ reports/${{ github.ref_name }}/jacoco

      - name: Upload dos reports
        uses: actions/upload-artifact@v4
        with:
          name: "reports-${{ github.ref_name }}"
          path: reports/${{ github.ref_name }}

  build:
    needs: analyse
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v4

      - name: Cache Maven
        uses: ./.github/workflows/maven-cache.yml

      - name: Configurar JDK (Java 21) e compilar projeto com Maven
        uses: ./.github/workflows/maven-compile.yml@main

      - name: Empacotar aplica칞칚o
        run: |
          echo "Empacotando aplica칞칚o"
          mvn package -Dgroups=!Selenium -B || {
            echo "::error::Falha ao empacotar o projeto. Verifique se os testes e build est칚o corretos.";
            exit 1;
          }

      - name: Upload artefato (.jar)
        uses: actions/upload-artifact@v4
        with:
          name: Rodrigo_Loureiro_PB_TP5
          path: target/*.jar

  deploy:
    name: Simula칞칚o de Deploy
    runs-on: ubuntu-latest
    needs:
      - analyse
      - build

    steps:
      - name: Baixar artefato do build
        uses: actions/download-artifact@v4
        with:
          name: Rodrigo_Loureiro_PB_TP5
          path: ./deploy

      - name: Simular processo de deploy
        run: echo "游 Iniciando simula칞칚o de deploy"

      - name: Finalizar deploy
        run: echo "Deploy finalizado"