name: Esteira CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  analyse:
    name: An√°lise do c√≥digo
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ "java" ]

    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v4

      - name: Criar pasta para os relat√≥rios
        run: mkdir -p reports/${{ github.head_ref || github.ref_name }}

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Inicializar CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: ${{ matrix.language }}
          queries: security-extended,security-and-quality

      - name: Configurar JDK (Java 21)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Compilar com Maven
        run: |
          mvn clean compile -B || { 
            echo "::error::Falha na compila√ß√£o do projeto. Verifique erros de sintaxe ou depend√™ncias ausentes."; 
            exit 1; 
          }

      - name: Executar an√°lise de CodeQL
        uses: github/codeql-action/analyze@v4
        with:
          output: reports/${{ github.head_ref || github.ref_name }}
          category: "/language:${{ matrix.language }}"

      - name: Renomear arquivo SARIF
        run: |
          ORIGINAL="reports/${{ github.head_ref || github.ref_name }}/${{ matrix.language }}.sarif"
          NOVO="reports/${{ github.head_ref || github.ref_name }}/codeql-results.sarif"
          mv "$ORIGINAL" "$NOVO"

      - name: Executar CLOC
        uses: djdefi/cloc-action@6
        with:
          options: --exclude-lang=YAML --md --report-file=cloc.md

      - name: Mover CLOC report
        run: mv cloc.md reports/${{ github.head_ref || github.ref_name }}/cloc.md

      - name: Executar Checkstyle (Maven)
        run: mvn checkstyle:checkstyle

      - name: Preparar pasta para report do Checkstyle
        run: mkdir -p reports/${{ github.head_ref || github.ref_name }}/checkstyle-result

      - name: Mover report Checkstyle
        run: |
          mv target/site/css reports/${{ github.head_ref || github.ref_name }}/checkstyle-result/css
          mv target/site/images reports/${{ github.head_ref || github.ref_name }}/checkstyle-result/images
          mv target/site/checkstyle.html reports/${{ github.head_ref || github.ref_name }}/checkstyle-result

      - name: Executar SpotBugs
        run: mvn spotbugs:spotbugs

      - name: Mover report SpotBugs
        run: |
          mv target/spotbugsXml.xml reports/${{ github.head_ref || github.ref_name }}/spotbugs.xml
          mv target/site/spotbugs.html reports/${{ github.head_ref || github.ref_name }}/spotbugs.html

      - name: Executar testes
        run: |
          mvn test -Dgroups=!Selenium -B || {
            echo "::error::Alguns testes falharam. Revise os logs para detalhes.";
            exit 1;
          }

      - name: Mover report JaCoCo
        run: mv target/site/jacoco/ reports/${{ github.head_ref || github.ref_name }}/jacoco

      - name: Upload dos reports
        uses: actions/upload-artifact@v4
        with:
          name: "reports-${{ github.head_ref || github.ref_name }}"
          path: reports/${{ github.head_ref || github.ref_name }}

  build:
    needs: analyse
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v4

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Configurar JDK (Java 21)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Compilar com Maven
        run: |
          mvn clean compile -B || { 
            echo "::error::Falha na compila√ß√£o do projeto. Verifique erros de sintaxe ou depend√™ncias ausentes."; 
            exit 1; 
          }

      - name: Empacotar aplica√ß√£o
        run: |
          echo "Empacotando aplica√ß√£o"
          mvn package -Dgroups=!Selenium -B || {
            echo "::error::Falha ao empacotar o projeto. Verifique se os testes e build est√£o corretos.";
            exit 1;
          }

      - name: Upload artefato (.jar)
        uses: actions/upload-artifact@v4
        with:
          name: Rodrigo_Loureiro_PB_TP5
          path: target/*.jar

  deploy-dev:
    name: Deploy DEV
    environment: dev
    runs-on: ubuntu-latest
    needs:
      - analyse
      - build

    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN_DEV}}

      - name: Gerar imagem docker
        run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/rodrigoloureiro-tp5:dev

      - name: Docker Push DEV
        run: |
          echo "üöÄ Iniciando deploy em desenvolvimento"
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rodrigoloureiro-tp5:dev
          echo "Deploy em desenvolvimento finalizado"

  deploy-homol:
    name: Deploy HOMOL
    environment: homol
    runs-on: ubuntu-latest
    needs:
      - deploy-dev

    steps:
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN_HOMOL}}

      - name: Docker Push HOMOL
        run: |
          echo "üöÄ Iniciando deploy em homologa√ß√£o"
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/rodrigoloureiro-tp5:dev
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/rodrigoloureiro-tp5:dev \
            ${{ secrets.DOCKERHUB_USERNAME }}/rodrigoloureiro-tp5:homol
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rodrigoloureiro-tp5:homol
          echo "Deploy em homologa√ß√£o finalizado"

  deploy-prod:
    name: Deploy PROD
    environment: prod
    runs-on: ubuntu-latest
    needs:
      - deploy-homol

    steps:
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN_PROD}}

      - name: Docker Push PROD
        run: |
          echo "üöÄ Iniciando deploy em produ√ß√£o"
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/rodrigoloureiro-tp5:homol
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/rodrigoloureiro-tp5:homol \
            ${{ secrets.DOCKERHUB_USERNAME }}/rodrigoloureiro-tp5:prod
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rodrigoloureiro-tp5:prod
          echo "Deploy em produ√ß√£o finalizado"